### ISSUE TITLE
"make client process failed" when start to edit markdown file

### ISSUE THREAD

**Issue by ghost** [ancane/markdown-preview-mode#31]
"File mode specification error: (file-error make client process failed Connection refused :name websocket to ws://localhost:7379 :buffer nil :host loc\
alhost :service 7379 :nowait nil)"

**Comment by ghost** [comment]
i install the package with melpa, here is my config info:
```lisp
;; markdown-preview-mode
(require 'markdown-preview-mode)
(add-hook 'markdown-mode-hook 'markdown-preview-mode)
(add-hook 'kill-buffer-hook 'markdown-preview-cleanup)
```

**Comment by ancane** [comment]
@ycz0926 Hi. Sorry it didn't work for you out of the box. I can advise couple things for debugging.
1. Please, check if your PATH has a markdown processor command. Also it's possible to check it, running `markdown-preview` which triggers the original markdown-mode preview window.
2. Try running emacs with `(setq debug-on-error t)` and capturing error stack trace.
3. Make sure no antivirus/firewall/etc is blocking 7379 port from listening.
4. Provide your OS/emacs version, websocket.el version and markdown mode version so that I could check for possible websocket issues in your setup.
Thanks.

**Comment by ghost** [comment]
thanks, it's ok now
